Task5
hawk911/RoR_extended pull request #6
Opened 2016-08-23 05:22 UTC by hawk911

2016-08-25 02:55 UTC, yogadeveloper commented on db/migrate/20160824181142_add_user_to_questions.rb
> +    add_index :questions, :user_id
можно это записать проще 

>  add_reference :questions, :user, index: true, foreign_key: true

2016-09-22 14:35 UTC, palkan requested changes

2016-09-22 14:35 UTC, palkan commented on .rake_tasks~
> +about
Пожалуй, этому файлу не место в репозитории.

2016-09-22 14:35 UTC, palkan commented on spec/feature/answers/create_answer_spec.rb
> +      within 'body' do
Это лучше добавить в предыдущий сценарий и добавить тэг `:aggregate_failures`:

``` ruby
scenario "...", :aggragate_failures do
...
end
```

Данные проверки независимы, будет лучше объединить их в одном сценарии – это ускорить тесты.

2016-09-22 14:35 UTC, palkan commented on spec/feature/questions/show_question_and_answers_spec.rb
> +        question_with_answers.answers. each do |answer|
У тебя все ответы, создаваемые фабрикой, имеют одинаковый body; так что тест этот не проверяет вывод списка, даже если будет показывать один ответ, он пройдет.

Нужно сделать в фабрике так, чтобы текстовые поля были уникальными.

2016-09-22 14:35 UTC, palkan commented on spec/feature/questions/show_questions_list_spec.rb
> +  given!(:questions) { create_list(:question, 3) }
Во-первых, достаточно 2х.
Во-вторых, та же проблема, что и с ответами – тексты одинаковые для всех вопросов.

2016-09-22 14:35 UTC, palkan commented on spec/feature/questions/show_questions_list_spec.rb
> +      expect(page).to have_css('.questions div', count: 3)
Проверять нужно контент, а не CSS, пользователь в код страницы не смотрит.

2016-09-22 14:35 UTC, palkan commented on spec/factories/questions.rb
> +        create_list(:answer, 4, question: question)
Зачем 4? Достаточно 2х.

2016-09-23 04:52 UTC, hawk911 commented on spec/factories/questions.rb
> +        create_list(:answer, 4, question: question)
Я пробовал, а то надоело везде 2 :)

2016-09-23 08:11 UTC, vkurennov commented on app/models/answer.rb
>    validates :body, :question_id, presence: true
А валидация на user_id?

2016-09-23 08:12 UTC, vkurennov commented on app/controllers/questions_controller.rb
>  class QuestionsController < ApplicationController
Нет проверки на авторство при удалении вопроса

2016-09-23 08:12 UTC, vkurennov commented on app/models/question.rb
> +  scope :ordered, -> { order(created_at: :desc) }
Скоупы пишут после ассоциаций и валидаций

2016-09-23 08:13 UTC, vkurennov commented on app/models/question.rb
> +  belongs_to :user
Нужна валидация на user_id

2016-09-23 08:14 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>        it 'saves the new answer in the base' do
Нужен тест на то, что созданный ответ связывается с залогиненным пользователем

2016-09-23 08:15 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with validate attributes' do
Нужен тест на то, что созданный вопрос связывается с залогиненным пользователем

2016-09-23 08:17 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
Тут нужно 2 контекста: для автора и для не-автора

2016-09-23 08:17 UTC, vkurennov commented on spec/feature/answers/destroy_answer_spec.rb
> +  given(:question_path) { "/questions/#{question.id}" }
Используй url-хелперы

2016-09-23 08:19 UTC, vkurennov requested changes
Исправь замечания

2016-09-24 11:39 UTC, hawk911 commented on spec/feature/answers/destroy_answer_spec.rb
> +  given(:question_path) { "/questions/#{question.id}" }
Не много не понял, но вроде given(:user_question_path) { questions_path(question) }

2016-09-24 15:13 UTC, vkurennov commented on app/controllers/answers_controller.rb
>      @answer = Answer.new
У тебя форма создания ответа должна быть на странице вопроса, значит new тебе не нужен

2016-09-24 15:15 UTC, vkurennov commented on app/models/question.rb
> +
Зачем валидировать и user и user_id, достаточно только последнего

2016-09-24 15:21 UTC, vkurennov approved these changes
Принято

2016-09-25 17:42 UTC, merged