Task8
hawk911/RoR_extended pull request #9
Opened 2016-10-24 08:16 UTC by hawk911

2016-11-09 16:53 UTC, vkurennov requested changes
Сделай возможность удаления файлов без редактирования объекта, т.е. просто ссылка на удаление рядом с файлом

2016-11-10 09:01 UTC, vkurennov requested changes

2016-11-10 09:01 UTC, vkurennov commented on spec/feature/questions/delete_files_to_question_spec.rb
> +      expect(page).to_not have_link I18n.t('questions.form.delete_file')
Так мы не ссылку должны проверять, а удаление файла, т.е. ссылки на прикрепленный файл не должно быть

2016-11-10 09:01 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +          patch :update, params: {
Ну вот в том-то и дело, что сделав такой запрос, ты файл удалишь, но ссылка твоя не делает такой запрос и ничего в базе не удаляет.

2016-11-10 09:01 UTC, vkurennov commented on spec/feature/questions/delete_files_to_question_spec.rb
> +      expect(page).to_not have_link I18n.t('questions.form.delete_file')
И надо, чтобы файл физически удалялся, просто убрать его со страницы смысла нет, он после перезагрузки останется. Измени тест так: заходим на страницу, проверяем что ссылка на файл есть, кликаем по удалению, снова заходим на эту страницу, проверяем, что ссылки на файл нет.

2016-11-14 10:53 UTC, vkurennov commented on spec/feature/answers/add_files_to_answer_spec.rb
> +      fill_in 'answer_body', with: 'answer'
У поля точно id answer_body?

2016-11-15 05:03 UTC, hawk911 commented on spec/feature/answers/add_files_to_answer_spec.rb
> +      fill_in 'answer_body', with: 'answer'
Да, точно.

2016-11-15 13:10 UTC, vkurennov approved these changes

2016-11-15 13:10 UTC, vkurennov commented on app/controllers/attachments_controller.rb
> +    @attachment.destroy if @attachment && current_user.author_of?(@attachment.attachable)
проверка на наличие @attachment лишняя, т.к. find выбросит исключение, если не найдет запись с id, соответственно дальнейший код не будет выполняться.

2016-11-16 04:02 UTC, merged